from enum import Enum
from pathlib import Path

from pydantic import Field
from pydantic_settings import BaseSettings, SettingsConfigDict


class GameMode(Enum):
    """
    Definition of Game Modes. The enum value also represents the token length used in this game mode.
    """
    NORMAL = 1
    HARD = 2


# settings class exists here directly and not in model.py to avoid cyclic imports
class Settings(BaseSettings):
    single_player: bool = Field(default=False)
    bots_allowed: bool = Field(default=False)
    admin_guild_id: int = Field(default=None, validate_default=True)
    token: str = Field(default=None, validate_default=True)
    command_signature_file: str | Path = Field(default="command_signature.json")

    model_config = SettingsConfigDict(env_file='.env')


SETTINGS = Settings()
"""Application wide settings object."""

# Names of individual cogs
COG_NAME_COMMON: str = "common"
COG_NAME_ADMIN_CMDS: str = "admin_cmds"
COG_NAME_MANAGER_CMDS: str = "manager_cmds"
COG_NAME_USER_CMDS: str = "user_cmds"
COG_NAME_GAME: str = "game"

COGS_LIST: list[str] = [COG_NAME_COMMON, COG_NAME_ADMIN_CMDS, COG_NAME_MANAGER_CMDS, COG_NAME_USER_CMDS, COG_NAME_GAME]
"""List of all cogs."""

# Names of individual loggers
LOGGER_NAME_MAIN: str = "__main__"
LOGGER_NAME_COMMON_COG: str = f"__{COG_NAME_COMMON}__"
LOGGER_NAME_ADMIN_COG: str = f"__{COG_NAME_ADMIN_CMDS}__"
LOGGER_NAME_MANAGER_COG: str = f"__{COG_NAME_MANAGER_CMDS}__"
LOGGER_NAME_USER_COG: str = f"__{COG_NAME_USER_CMDS}__"
LOGGER_NAME_GAME_COG: str = f"__{COG_NAME_GAME}__"

LOGGERS_LIST: list[str] = [LOGGER_NAME_MAIN, LOGGER_NAME_COMMON_COG, LOGGER_NAME_ADMIN_COG, LOGGER_NAME_MANAGER_COG, LOGGER_NAME_USER_COG, LOGGER_NAME_GAME_COG]
"""List of all loggers."""

HISTORY_LENGTH: int = 5
"""Amount of words kept in history per user"""

MISTAKE_PENALTY: int = 5
"""Amount of karma subtracted for a mistake"""

RELIABLE_ROLE_KARMA_THRESHOLD: int = 25
"""Minimum karma needed for the reliable role"""

RELIABLE_ROLE_ACCURACY_THRESHOLD: float = .975
"""Minimum accuracy needed for the reliable role"""

SPECIAL_REACTION_EMOJIS: dict[str, str] = {
    'afghanistan': '🇦🇫',
    'albania': '🇦🇱',
    'algeria': '🇩🇿',
    'andorra': '🇦🇩',
    'angola': '🇦🇴',
    'anguilla': '🇦🇮',
    'antarctica': '🇦🇶',
    'antigua': '🇦🇬',
    'ascension': '🇦🇨',
    'barbuda': '🇦🇬',
    'argentina': '🇦🇷',
    'armenia': '🇦🇲',
    'aruba': '🇦🇼',
    'australia': '🇦🇺',
    'austria': '🇦🇹',
    'azerbaijan': '🇦🇿',
    'bahamas': '🇧🇸',
    'bahrain': '🇧🇭',
    'bangladesh': '🇧🇩',
    'barbados': '🇧🇧',
    'belarus': '🇧🇾',
    'belgium': '🇧🇪',
    'belize': '🇧🇿',
    'benin': '🇧🇯',
    'bermuda': '🇧🇲',
    'bhutan': '🇧🇹',
    'bolivia': '🇧🇴',
    'bonaire': '🇧🇶',
    'bosnia': '🇧🇦',
    'herzegovina': '🇧🇦',
    'botswana': '🇧🇼',
    'bouvet': '🇧🇻',
    'brazil': '🇧🇷',
    'brunei': '🇧🇳',
    'bulgaria': '🇧🇬',
    'burkina': '🇧🇫',
    'burundi': '🇧🇮',
    'cambodia': '🇰🇭',
    'cameroon': '🇨🇲',
    'canada': '🇨🇦',
    'cayman': '🇰🇾',
    'chad': '🇹🇩',
    'chile': '🇨🇱',
    'china': '🇨🇳',
    'colombia': '🇨🇴',
    'comoros': '🇰🇲',
    'congo': '🇨🇩',
    'croatia': '🇭🇷',
    'cuba': '🇨🇺',
    'cyprus': '🇨🇾',
    'czechia': '🇨🇿',
    'denmark': '🇩🇰',
    'djibouti': '🇩🇯',
    'dominica': '🇩🇲',
    'dominican': '🇩🇴',
    'ecuador': '🇪🇨',
    'egypt': '🇪🇬',
    'salvador': '🇸🇻',
    'eritrea': '🇪🇷',
    'estonia': '🇪🇪',
    'eswatini': '🇸🇿',
    'ethiopia': '🇪🇹',
    'fiji': '🇫🇯',
    'finland': '🇫🇮',
    'france': '🇫🇷',
    'gabon': '🇬🇦',
    'gambia': '🇬🇲',
    'georgia': '🇬🇪',
    'germany': '🇩🇪',
    'ghana': '🇬🇭',
    'gibraltar': '🇬🇮',
    'greece': '🇬🇷',
    'greenland': '🇬🇱',
    'grenada': '🇬🇩',
    'guadeloupe': '🇬🇵',
    'guam': '🇬🇺',
    'guatemala': '🇬🇹',
    'guernsey': '🇬🇬',
    'guinea': '🇬🇳',
    'guinea-bissau': '🇬🇼',
    'guyana': '🇬🇾',
    'haiti': '🇭🇹',
    'vatican': '🇻🇦',
    'honduras': '🇭🇳',
    'hungary': '🇭🇺',
    'iceland': '🇮🇸',
    'india': '🇮🇳',
    'bharat': '🇮🇳',
    'indonesia': '🇮🇩',
    'iran': '🇮🇷',
    'iraq': '🇮🇶',
    'ireland': '🇮🇪',
    'israel': '🇮🇱',
    'italy': '🇮🇹',
    'jamaica': '🇯🇲',
    'japan': '🇯🇵',
    'jersey': '🇯🇪',
    'jordan': '🇯🇴',
    'kazakhstan': '🇰🇿',
    'kenya': '🇰🇪',
    'kiribati': '🇰🇮',
    'korea': '🇰🇷',
    'kuwait': '🇰🇼',
    'kyrgyzstan': '🇰🇬',
    "laos": '🇱🇦',
    'latvia': '🇱🇻',
    'lebanon': '🇱🇧',
    'lesotho': '🇱🇸',
    'liberia': '🇱🇷',
    'libya': '🇱🇾',
    'liechtenstein': '🇱🇮',
    'lithuania': '🇱🇹',
    'luxembourg': '🇱🇺',
    'macao': '🇲🇴',
    'madagascar': '🇲🇬',
    'malawi': '🇲🇼',
    'malaysia': '🇲🇾',
    'maldives': '🇲🇻',
    'mali': '🇲🇱',
    'malta': '🇲🇹',
    'martinique': '🇲🇶',
    'mauritania': '🇲🇷',
    'mauritius': '🇲🇺',
    'mayotte': '🇾🇹',
    'mexico': '🇲🇽',
    'micronesia': '🇫🇲',
    'moldova': '🇲🇩',
    'monaco': '🇲🇨',
    'mongolia': '🇲🇳',
    'montenegro': '🇲🇪',
    'montserrat': '🇲🇸',
    'morocco': '🇲🇦',
    'mozambique': '🇲🇿',
    'myanmar': '🇲🇲',
    'namibia': '🇳🇦',
    'nauru': '🇳🇷',
    'nepal': '🇳🇵',
    'netherlands': '🇳🇱',
    'caledonia': '🇳🇨',
    'zealand': '🇳🇿',
    'nicaragua': '🇳🇮',
    'niger': '🇳🇪',
    'nigeria': '🇳🇬',
    'niue': '🇳🇺',
    'norfolk': '🇳🇫',
    'macedonia': '🇲🇰',
    'norway': '🇳🇴',
    'oman': '🇴🇲',
    'pakistan': '🇵🇰',
    'palau': '🇵🇼',
    'palestine': '🇵🇸',
    'panama': '🇵🇦',
    'papua new guinea': '🇵🇬',
    'paraguay': '🇵🇾',
    'peru': '🇵🇪',
    'philippines': '🇵🇭',
    'pitcairn': '🇵🇳',
    'poland': '🇵🇱',
    'portugal': '🇵🇹',
    'puerto': '🇵🇷',
    'qatar': '🇶🇦',
    'romania': '🇷🇴',
    'rwanda': '🇷🇼',
    'samoa': '🇼🇸',
    'arabia': '🇸🇦',
    'saudi': '🇸🇦',
    'senegal': '🇸🇳',
    'serbia': '🇷🇸',
    'seychelles': '🇸🇨',
    'singapore': '🇸🇬',
    'slovakia': '🇸🇰',
    'slovenia': '🇸🇮',
    'solomon': '🇸🇧',
    'somalia': '🇸🇴',
    'spain': '🇪🇸',
    'lanka': '🇱🇰',
    'sudan': '🇸🇩',
    'suriname': '🇸🇷',
    'sweden': '🇸🇪',
    'switzerland': '🇨🇭',
    'syria': '🇸🇾',
    'taiwan': '🇹🇼',
    'tajikistan': '🇹🇯',
    'tanzania': '🇹🇿',
    'thailand': '🇹🇭',
    'timor-leste': '🇹🇱',
    'togo': '🇹🇬',
    'tokelau': '🇹🇰',
    'tonga': '🇹🇴',
    'trinidad': '🇹🇹',
    'tobago': '🇹🇹',
    'tunisia': '🇹🇳',
    'turkmenistan': '🇹🇲',
    'tuvalu': '🇹🇻',
    'turkey': '🦃',
    'türkiye': '🇹🇷',
    'uganda': '🇺🇬',
    'ukraine': '🇺🇦',
    'emirates': '🇦🇪',
    'uk': '🇬🇧',
    'britain': '🇬🇧',
    'england': "🏴󠁧󠁢󠁥󠁮󠁧󠁿",
    'scotland': "🏴󠁧󠁢󠁳󠁣󠁴󠁿",
    'wales': "🏴󠁧󠁢󠁷󠁬󠁳󠁿",
    'usa': '🇺🇸',
    'america': '🇺🇸',
    'uruguay': '🇺🇾',
    'uzbekistan': '🇺🇿',
    'vanuatu': '🇻🇺',
    'venezuela': '🇻🇪',
    'vietnam': '🇻🇳',
    'yemen': '🇾🇪',
    'zambia': '🇿🇲',
    'zimbabwe': '🇿🇼',
    'russia': '🇷🇺'
}
"""
A dictionary mapping the words to the corresponding special emojis.
"""

GLOBAL_BLACKLIST_2_LETTER_WORDS_EN: set[str] = {
    'aa',
    'ab',
    'ac',
    'ad',
    'ae',
    'af',
    'ag',
    'ah',
    'ai',
    'aj',
    'ak',
    'al',
    'ao',
    'ap',
    'aq',
    'ar',
    'au',
    'av',
    'aw',
    'ax',
    'ay',
    'az',
    'ba',
    'bb',
    'bc',
    'bd',
    'bf',
    'bg',
    'bh',
    'bi',
    'bj',
    'bk',
    'bl',
    'bm',
    'bn',
    'bo',
    'bp',
    'bq',
    'br',
    'bs',
    'bt',
    'bu',
    'bv',
    'bw',
    'bx',
    'bz',
    'ca',
    'cb',
    'cc',
    'cd',
    'ce',
    'cf',
    'cg',
    'ch',
    'ci',
    'cj',
    'ck',
    'cl',
    'cm',
    'cn',
    'co',
    'cp',
    'cq',
    'cr',
    'cs',
    'ct',
    'cu',
    'cv',
    'cw',
    'cx',
    'cy',
    'cz',
    'da',
    'db',
    'dc',
    'dd',
    'de',
    'df',
    'dg',
    'dh',
    'di',
    'dj',
    'dk',
    'dl',
    'dm',
    'dn',
    'dp',
    'dq',
    'dr',
    'ds',
    'dt',
    'du',
    'dv',
    'dw',
    'dx',
    'dy',
    'dz',
    'ea',
    'eb',
    'ec',
    'ed',
    'ee',
    'ef',
    'eg',
    'eh',
    'ei',
    'ej',
    'ek',
    'el',
    'em',
    'en',
    'eo',
    'ep',
    'eq',
    'er',
    'es',
    'et',
    'eu',
    'ev',
    'ew',
    'ex',
    'ey',
    'ez',
    'fa',
    'fb',
    'fc',
    'fd',
    'fe',
    'ff',
    'fg',
    'fh',
    'fi',
    'fj',
    'fk',
    'fl',
    'fm',
    'fn',
    'fo',
    'fp',
    'fq',
    'fr',
    'fs',
    'ft',
    'fu',
    'fv',
    'fw',
    'fx',
    'fy',
    'fz',
    'ga',
    'gb',
    'gc',
    'gd',
    'ge',
    'gf',
    'gg',
    'gh',
    'gi',
    'gj',
    'gk',
    'gl',
    'gm',
    'gn',
    'gp',
    'gq',
    'gr',
    'gs',
    'gt',
    'gu',
    'gv',
    'gw',
    'gx',
    'gy',
    'gz',
    'ha',
    'hb',
    'hc',
    'hd',
    'hf',
    'hg',
    'hh',
    'hj',
    'hk',
    'hl',
    'hm',
    'hn',
    'ho',
    'hp',
    'hq',
    'hr',
    'hs',
    'ht',
    'hu',
    'hv',
    'hw',
    'hx',
    'hy',
    'hz',
    'ia',
    'ib',
    'ic',
    'id',
    'ie',
    'ig',
    'ih',
    'ii',
    'ij',
    'ik',
    'il',
    'im',
    'io',
    'ip',
    'iq',
    'ir',
    'iu',
    'iv',
    'iw',
    'ix',
    'iy',
    'iz',
    'ja',
    'jb',
    'jc',
    'jd',
    'je',
    'jf',
    'jg',
    'jh',
    'ji',
    'jj',
    'jk',
    'jl',
    'jm',
    'jn',
    'jo',
    'jp',
    'jq',
    'jr',
    'js',
    'jt',
    'ju',
    'jv',
    'jw',
    'jx',
    'jy',
    'jz',
    'ka',
    'kb',
    'kc',
    'kd',
    'ke',
    'kf',
    'kg',
    'kh',
    'ki',
    'kj',
    'kk',
    'kl',
    'km',
    'kn',
    'ko',
    'kp',
    'kq',
    'kr',
    'ks',
    'kt',
    'ku',
    'kv',
    'kw',
    'kx',
    'ky',
    'kz',
    'la',
    'lb',
    'lc',
    'ld',
    'le',
    'lf',
    'lg',
    'lh',
    'li',
    'lj',
    'lk',
    'll',
    'lm',
    'ln',
    'lo',
    'lp',
    'lq',
    'lr',
    'ls',
    'lt',
    'lu',
    'lv',
    'lw',
    'lx',
    'ly',
    'lz',
    'ma',
    'mb',
    'mc',
    'md',
    'mf',
    'mg',
    'mh',
    'mi',
    'mj',
    'mk',
    'ml',
    'mm',
    'mn',
    'mo',
    'mp',
    'mq',
    'mr',
    'ms',
    'mt',
    'mu',
    'mv',
    'mw',
    'mx',
    'mz',
    'na',
    'nb',
    'nc',
    'nd',
    'ne',
    'nf',
    'ng',
    'nh',
    'ni',
    'nj',
    'nk',
    'nl',
    'nm',
    'nn',
    'np',
    'nq',
    'nr',
    'ns',
    'nt',
    'nu',
    'nv',
    'nw',
    'nx',
    'ny',
    'nz',
    'oa',
    'ob',
    'oc',
    'od',
    'oe',
    'og',
    'oi',
    'oj',
    'ok',
    'ol',
    'om',
    'oo',
    'op',
    'oq',
    'os',
    'ot',
    'ou',
    'ov',
    'ow',
    'oy',
    'oz',
    'pa',
    'pb',
    'pc',
    'pd',
    'pe',
    'pf',
    'pg',
    'ph',
    'pj',
    'pk',
    'pl',
    'pm',
    'pn',
    'po',
    'pp',
    'pq',
    'pr',
    'ps',
    'pt',
    'pu',
    'pv',
    'pw',
    'px',
    'py',
    'pz',
    'qa',
    'qb',
    'qc',
    'qd',
    'qe',
    'qf',
    'qg',
    'qh',
    'qi',
    'qj',
    'qk',
    'ql',
    'qm',
    'qn',
    'qo',
    'qp',
    'qq',
    'qr',
    'qs',
    'qt',
    'qu',
    'qv',
    'qw',
    'qx',
    'qy',
    'qz',
    'ra',
    'rb',
    'rc',
    'rd',
    're',
    'rf',
    'rg',
    'rh',
    'ri',
    'rj',
    'rk',
    'rl',
    'rm',
    'rn',
    'ro',
    'rp',
    'rq',
    'rr',
    'rs',
    'rt',
    'ru',
    'rv',
    'rw',
    'rx',
    'ry',
    'rz',
    'sa',
    'sb',
    'sc',
    'sd',
    'se',
    'sf',
    'sg',
    'sh',
    'si',
    'sj',
    'sk',
    'sl',
    'sm',
    'sn',
    'sp',
    'sq',
    'sr',
    'ss',
    'st',
    'su',
    'sv',
    'sw',
    'sx',
    'sy',
    'sz',
    'ta',
    'tb',
    'tc',
    'td',
    'te',
    'tf',
    'tg',
    'th',
    'ti',
    'tj',
    'tk',
    'tl',
    'tm',
    'tn',
    'tp',
    'tq',
    'tr',
    'ts',
    'tt',
    'tu',
    'tv',
    'tw',
    'tx',
    'ty',
    'tz',
    'ua',
    'ub',
    'uc',
    'ud',
    'ue',
    'uf',
    'ug',
    'uh',
    'ui',
    'uj',
    'ul',
    'um',
    'un',
    'uo',
    'up',
    'uq',
    'ur',
    'ut',
    'uu',
    'uv',
    'uw',
    'ux',
    'uy',
    'uz',
    'va',
    'vb',
    'vc',
    'vd',
    've',
    'vf',
    'vg',
    'vh',
    'vi',
    'vj',
    'vk',
    'vl',
    'vm',
    'vn',
    'vo',
    'vp',
    'vq',
    'vr',
    'vs',
    'vt',
    'vu',
    'vv',
    'vw',
    'vx',
    'vy',
    'vz',
    'wa',
    'wb',
    'wc',
    'wd',
    'wf',
    'wg',
    'wh',
    'wi',
    'wj',
    'wk',
    'wl',
    'wm',
    'wn',
    'wo',
    'wp',
    'wq',
    'wr',
    'ws',
    'wt',
    'wu',
    'wv',
    'ww',
    'wx',
    'wy',
    'wz',
    'xa',
    'xb',
    'xc',
    'xd',
    'xe',
    'xf',
    'xg',
    'xh',
    'xi',
    'xj',
    'xk',
    'xl',
    'xm',
    'xn',
    'xo',
    'xp',
    'xq',
    'xr',
    'xs',
    'xt',
    'xu',
    'xv',
    'xw',
    'xx',
    'xy',
    'xz',
    'ya',
    'yb',
    'yc',
    'yd',
    'ye',
    'yf',
    'yg',
    'yh',
    'yi',
    'yj',
    'yk',
    'yl',
    'ym',
    'yn',
    'yo',
    'yp',
    'yq',
    'yr',
    'ys',
    'yt',
    'yu',
    'yv',
    'yw',
    'yx',
    'yy',
    'yz',
    'za',
    'zb',
    'zc',
    'zd',
    'ze',
    'zf',
    'zg',
    'zh',
    'zi',
    'zj',
    'zk',
    'zl',
    'zm',
    'zn',
    'zo',
    'zp',
    'zq',
    'zr',
    'zs',
    'zt',
    'zu',
    'zv',
    'zw',
    'zx',
    'zy',
    'zz'
}
"""
A list of 2-letter words that are not legal words.
"""

GLOBAL_BLACKLIST_N_LETTER_WORDS_EN: set[str] = {
    'aaaa',
    'bbbb',
    'cccc',
    'dddd',
    'hhhh',
    'iiii',
    'mmmm',
    'tttt',
    'xxxx',
    'lmao',
    'imho',
    'afaik',
    'otoh',
    'stoopid',
    'poon',
    'aaaaa',
    'wwwww',
    'iiiiii',
    'mmmmmm',
    'pppppp'
}
"""
A list of N-letter words that are not legal words (N > 3).
"""
