"""Multi-language

Revision ID: 3c0da61070c4
Revises: 20d8d765f2f9
Create Date: 2025-08-29 16:44:31.441622

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c0da61070c4'
down_revision: Union[str, None] = '20d8d765f2f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:

    with op.batch_alter_table('server_config', schema=None) as batch_op:
        batch_op.add_column(sa.Column('languages', sa.String(), nullable=True, default='en'))

    op.execute('UPDATE server_config SET languages = \'en\' WHERE languages IS NULL')

    with op.batch_alter_table('server_config', schema=None) as batch_op:
        batch_op.alter_column('languages', nullable=False)

    with op.batch_alter_table('word_cache', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(), nullable=True, default='en'))

    op.execute('UPDATE word_cache SET language = \'en\' WHERE language IS NULL')

    with op.batch_alter_table('word_cache', schema=None) as batch_op:
        batch_op.alter_column('language', nullable=False)


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('word_cache', schema=None) as batch_op:
        batch_op.drop_column('language')

    with op.batch_alter_table('server_config', schema=None) as batch_op:
        batch_op.drop_column('languages')

    # ### end Alembic commands ###
